#DO NOT MODIFY! AUTOMATICALLY GENERATED FILE!
_('Client')
_('Client|City')
_('Client|Company')
_('Client|Email')
_('Client|Name')
_('Client|State')
_('Client|Street')
_('Client|Zip')
_('Project')
_('Project|Name')
_('Time entry')
_('TimeEntry|Date')
_('TimeEntry|Description')
_('TimeEntry|Hours')
_('TimeEntry|Notes')
_('User')
_('User|City')
_('User|Company')
_('User|Current sign in at')
_('User|Current sign in ip')
_('User|Email')
_('User|Encrypted password')
_('User|Last sign in at')
_('User|Last sign in ip')
_('User|Name')
_('User|Remember created at')
_('User|Reset password sent at')
_('User|Reset password token')
_('User|Sign in count')
_('User|State')
_('User|Street')
_('User|Time zone')
_('User|Zip')
#DO NOT MODIFY! AUTOMATICALLY GENERATED FILE!
