# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f01ff6e495b12a201aad476323fed52a223388707019c18ad2e7dd542865ce2e81a985faf26d1105f1ba30c3668c91282c998902aee59f90a813b2f09b52cce

test:
  secret_key_base: 118ba312d0c39473a6703876da2d30c4887e077adacda844a2b690f49c62f840770a8f4d40422f5ad1d4d8ce3ea7eba129667ca364324a8f27da7f397364ae7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
